exhibit/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('signup/', views.SignUp.as_view(), name='signup'),
]

exhibit/blog/urls.py
from django.urls import path, include
from blog import views

# app_name not needed in project with only one application
app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.PostCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/new/cloud_images/', views.get_cloud_images, name='get_cloud_images'),
]

exhibit/exhibit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('project/', include('project.urls', namespace='project')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exhibit/project/urls.py
from django.urls import path
from project import views


app_name = 'project'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
]

exhibit/accounts/models.py
from django.db import models

# Create your models here.

exhibit/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from datetime import datetime
from markdownx.models import MarkdownxField
from cloudinary.models import CloudinaryField


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    text = MarkdownxField()
    thumbnail = CloudinaryField(blank=True, null=True, resource_type='image')
    create_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.publish_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments',
                             on_delete=models.CASCADE)
    author = models.CharField(max_length=256)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

exhibit/blog/forms.py
from django import forms
from markdownx.fields import MarkdownxFormField
from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    # image = CloudinaryJsFileField()

    class Meta():
        model = Post
        fields = ('author', 'title', 'text', 'thumbnail')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': MarkdownxFormField()
        }


class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
        }

exhibit/accounts/views.py
from django.shortcuts import render

# Create your views here.

exhibit/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils import timezone
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)

from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm

from cloudinary.api import resources_by_tag


# Create your views here.
class PostListView(ListView):
    model = Post
    paginate_by = 2

    def get_queryset(self):
        # field lookup: __lte -> less than or equal to
        return Post.objects.filter(publish_date__lte=timezone.now()).order_by('-publish_date')


class PostDetailView(DetailView):
    model = Post


class PostCreateView(CreateView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class PostUpdateView(UpdateView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class PostDeleteView(DeleteView, LoginRequiredMixin):
    model = Post
    success_url = reverse_lazy('post_list')


class DraftListView(ListView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post
    template_name = 'blog/post_draft_list.html'

    def get_queryset(self):
        return Post.objects.filter(publish_date__isnull=True).order_by('create_date')


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)


############################# Comment Views ###################################

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()

    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)


############################# AJAX Requests ###################################

def get_cloud_images(request):
    image_data = resources_by_tag("blog")
    return JsonResponse(image_data)

exhibit/exhibit/views.py
from django.views.generic import TemplateView
from django.utils import timezone
from blog.models import Post


class HomePage(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_posts'] = Post.objects.filter(publish_date__lte=timezone.now()).order_by('-publish_date')[:3]
        return context


class AboutView(TemplateView):
    template_name = 'about.html'

exhibit/project/views.py
from django.shortcuts import render
from django.views import generic


# Create your views here.
class ProjectListView(generic.TemplateView):
    template_name = 'project/index.html'

exhibit/accounts/templates/accounts/login.html
{%extends "base.html"%}
{%load bootstrap3%}
{%block content%}
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 my-5">
      <h3>Login</h3>
      <h6 class="text-muted">(Login only available for admin at this time.)</h6>
      <form method="post">
        {%csrf_token%}
        {%bootstrap_form form%}
        <input class="btn btn-default" type="submit" name="login" value="Login">
      </form>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>
{%endblock%}

exhibit/blog/templates/blog/markdownx/widget2.html
<div class="markdownx row">
    <div class="col-md-6">
        {% include 'django/forms/widgets/textarea.html' %}
    </div>
    <div class="col-md-6">
        <div class="markdownx-preview"></div>
    </div>
</div>

exhibit/blog/templates/blog/post_confirm_delete.html
{%extends "base.html"%}
{%block content%}
<form method="POST">
  {%csrf_token%}
  <p>Are you sure you want to delete <strong>{{object}}</strong>?</p>
  <input class="btn btn-danger" type="submit" value="Confirm">
</form>
{%endblock%}

exhibit/blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load custom %}
{% block content %}
<div class="row">
  <div class="col-md-8 blog-post">
    <h3 class="blog-post-title">{{ post.title }}</h3>
    <p class="post-content">
      {{ post.text|render_markdown|safe|linebreaksbr }}
    </p>
    {% if user.is_authenticated %}
      {% if post.publish_date %}
        <div class="date blog-post-meta">
          {{ post.publish_date }}
        </div>
      {% else %}
        <a class="btn btn-outline-primary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
      {% endif %}
      <a class="btn btn-outline-secondary" href="{% url 'blog:post_edit' pk=post.pk %}">Edit</a>
      <a class="btn btn-outline-danger" href="{% url 'blog:post_remove' pk=post.pk %}">Delete</a>
    {% endif %}
  </div>
  <div class="col-md-4">
    {% if post.thumbnail %}
      <a href="{% url 'blog:post_detail' pk=post.pk %}">
        <img class="img-thumbnail flex-auto d-none d-lg-block"
          src="{{ post.thumbnail.url }}" alt="Post thumbnail">
      </a>
    {% endif %}
  </div>
</div>
{% endblock %}

exhibit/blog/templates/blog/post_detail_stable.html
{%extends "base.html"%}
{%block content%}
<div class="row">
  <div class="col-md-8 blog-main">
    <div class="blog-post">
      <h2 class="blog-post-title">{{post.title}}</h2>
      <p class="blog-post-meta">{{post.publish_date}}</p>
      <p>{{post.text|safe|linebreaksbr}}</p>
    </div>
  </div>
</div>
{%endblock%}

exhibit/blog/templates/blog/post_draft_list.html
{%extends "base.html"%}
{%block content%}
{%for post in post_list%}
  <div class="blog-post">
    <h3 class="blog-post-title"><a href="{%url 'blog:post_detail' pk=post.pk%}">{{post.title}}</a></h3>
    <p class="date blog-post-meta">Created: {{post.create_date}}</p>
    <p>{{post.text|safe|truncatechars:200}}</p>
  </div>
{%endfor%}
{%endblock%}

exhibit/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 my-3">
    <div class="clearfix">
      <h3 class="float-left">New Post</h3>
      <button class="btn btn-default float-right" id="manage-photos"
        data-toggle="modal" data-target="#photoModal" type="button">
        View Uploaded Photos
      </button>
    </div>
    <form class="post-form" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-default save" type="submit">Save</button>
    </form>
    {{ form.media }}
  </div>
  <div class="col-md-3"></div>
</div>

<!-- Modal -->
<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Uploaded Photos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center px-3">
        <p class="text-muted">
          Copy and paste desired image links into post test field.
        </p>
        <div id="modal-body-content">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cloudinary-jquery-file-upload/2.5.0/cloudinary-jquery-file-upload.min.js"
  type="text/javascript">
</script>
<script type="text/javascript" src="{% static '/blog/js/cloudinary-widget.js' %}">
</script>
{% endblock %}

exhibit/blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load custom %}
{% block content %}
<div class="row">
  <div class="col-md-8 blog-main">
    <h3 class="pb-3 mb-4 font-italic border-bottom">
      My Blog
    </h3>
    {% for post in post_list %}
      <div class="card p-3">
        <div class="row">
          <div class="col-md-8">
            <h2 class="card-title">
              <a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
            </h2>
            <p class="card-subtitle text-muted">{{ post.publish_date }}</p>
            <p class="card-text">{{ post.text|render_markdown|safe|truncatewords:20 }}</p>
          </div>
          <div class="col-md-4">
            {% if post.thumbnail %}
              <a href="{% url 'blog:post_detail' pk=post.pk %}">
                <img class="img-thumbnail flex-auto d-none d-lg-block"
                  src="{{ post.thumbnail.url }}" alt="Post thumbnail">
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}

    <nav class="blog-pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1"
                class="btn btn-outline-primary">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}"
                class="btn btn-outline-primary">previous</a>
          {% endif %}

          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
          </span>

          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}"
                class="btn btn-outline-primary">next</a>
              <a href="?page={{ page_obj.paginator.num_pages }}"
                class="btn btn-outline-primary">last &raquo;</a>
          {% endif %}
      </span>
    </nav>
  </div>

  <aside class="col-md-4 blog-sidebar">
    <!-- <div class="p-3 mb-3 bg-light rounded">
      <h4 class="font-italic">About</h4>
      <p class="mb-0">Etiam porta <em>sem malesuada .</p>
    </div> -->

    <div class="p-3">
      <h4 class="font-italic">Archives</h4>
      <ol class="list-unstyled mb-0">
        <li><a href="#">March 2014</a></li>
        <li><a href="#">February 2014</a></li>
        <li><a href="#">January 2014</a></li>
      </ol>
    </div>

    <div class="p-3">
      <h4 class="font-italic">Elsewhere</h4>
      <ol class="list-unstyled">
        <li><a href="https://github.com/ddonco">GitHub</a></li>
        <li><a href="https://www.linkedin.com/in/dillondonohue/">LinkedIn</a></li>
        <li><a href="https://www.kaggle.com/ddonco">Kaggle</a></li>
      </ol>
    </div>
  </aside><!-- /.blog-sidebar -->

</div><!-- /.row -->
{% endblock %}

exhibit/blog/templates/blog/post_list_blogfmt.html
{% extends "base.html" %}
{% load custom %}
{% block content %}
<div class="row">
  <div class="col-md-8 blog-main">
    <h3 class="pb-3 mb-4 font-italic border-bottom">
      My Blog
    </h3>
    {% for post in post_list %}
      <div class="row blog-post">
        <div class="col-md-8">
          <h2 class="blog-post-title">
            <a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
          </h2>
          <p class="blog-post-meta">{{ post.publish_date }}</p>
          <p>{{ post.text|render_markdown|safe|truncatewords:20 }}</p>
        </div>
        <div class="col-md-4">
          {% if post.thumbnail %}
            <img class="img-thumbnail flex-auto d-none d-lg-block"
              src="{{ post.thumbnail.url }}" alt="Post thumbnail">
          {% endif %}
        </div>
      </div>
    {% endfor %}

    <nav class="blog-pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1"
                class="btn btn-outline-primary">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}"
                class="btn btn-outline-primary">previous</a>
          {% endif %}

          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
          </span>

          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}"
                class="btn btn-outline-primary">next</a>
              <a href="?page={{ page_obj.paginator.num_pages }}"
                class="btn btn-outline-primary">last &raquo;</a>
          {% endif %}
      </span>
    </nav>
  </div>

  <aside class="col-md-4 blog-sidebar">
    <!-- <div class="p-3 mb-3 bg-light rounded">
      <h4 class="font-italic">About</h4>
      <p class="mb-0">Etiam porta <em>sem malesuada .</p>
    </div> -->

    <div class="p-3">
      <h4 class="font-italic">Archives</h4>
      <ol class="list-unstyled mb-0">
        <li><a href="#">March 2014</a></li>
        <li><a href="#">February 2014</a></li>
        <li><a href="#">January 2014</a></li>
      </ol>
    </div>

    <div class="p-3">
      <h4 class="font-italic">Elsewhere</h4>
      <ol class="list-unstyled">
        <li><a href="https://github.com/ddonco">GitHub</a></li>
        <li><a href="https://www.linkedin.com/in/dillondonohue/">LinkedIn</a></li>
        <li><a href="https://www.kaggle.com/ddonco">Kaggle</a></li>
      </ol>
    </div>
  </aside><!-- /.blog-sidebar -->

</div><!-- /.row -->
{% endblock %}

exhibit/project/templates/project/index.html
{%extends "base.html"%}
{%load staticfiles%}
{%block content%}
<div class="container mt-3">
  <div class="row">
    <div id="ghapiprofile" class="col-md-6"></div>
    <div id="ghapidata" class="col-md-6"></div>
  </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="{%static 'project/js/github-data.js'%}"></script>

{%endblock%}

exhibit/templates/about.html
{%extends "base.html"%}
{%block content%}
<h1>About Me</h1>
{%endblock%}

exhibit/templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="#">

    <title>DDonohue</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
  </head>

  <body>

    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <!-- <a class="text-muted" href="#">Subscribe</a> -->
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'index' %}">DDonohue</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
              <span><i class="material-icons">person</i></span>
            </button>
            <!-- <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a> -->
          </div>
        </div>
      </header>
      <div class="collapse" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-md-right">
              <ul class="list-unstyled">
                {% if user.is_authenticated %}
                  <li class="my-2"><a href="{% url 'accounts:logout' %}" class="text-muted">Log Out</a></li>
                  <li class="my-2"><a href="{% url 'blog:post_new' %}" class="text-muted">New Post</a></li>
                  <li class="my-2"><a href="{% url 'blog:post_draft_list' %}" class="text-muted">Post Drafts</a></li>
                {% else %}
                  <li><a href="{% url 'accounts:login' %}" class="text-muted">Login</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="{% url 'index' %}">Welcome</a>
          <a class="p-2 text-muted" href="{% url 'about' %}">About</a>
          <a class="p-2 text-muted" href="{% url 'blog:post_list' %}">Blog</a>
          <a class="p-2 text-muted" href="{% url 'project:project_list' %}">Projects</a>
          <a class="p-2 text-muted disabled" href="#">Reads</a>
        </nav>
      </div>
      {%block content%}

      {%endblock%}
    </div>
    <footer class="blog-footer">
      <p><a href="#">Back to top</a></p>
      <p class="small">Blog template based on Bootstrap <a href="https://getbootstrap.com/docs/4.1/examples/">Blog Example</a>
    </footer>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
      integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
      crossorigin="anonymous"></script>
  </body>
</html>

exhibit/templates/index.html
{% extends "base.html" %}
{% load custom %}
{% block content %}
<div class="jumbotron pl-5 pr-1 py-1 text-white rounded bg-dark">
  <div class="row">
    <div class="col-md-8 px-0 pt-3">
      {% if latest_posts.0 %}
      <h1 class="display-4 font-italic">
        <a href="{% url 'blog:post_detail' pk=latest_posts.0.pk %}">
          {{ latest_posts.0.title }}</a></h1>
      <div class="mb-1 text-muted">{{ latest_posts.0.publish_date }}</div>
        <p class="lead my-3">
          {{ latest_posts.0.text|render_markdown|safe|truncatewords:20 }}
        </p>
        <p class="lead align-bottom mb-0 pb-0">
          <a href="{% url 'blog:post_detail' pk=latest_posts.0.pk %}"
            class="text-white font-weight-bold">Continue reading...</a>
        </p>
      {% endif %}
    </div>
    <div class="col-md-4">
      {% if latest_posts.0.thumbnail %}
        <img class="img-thumbnail flex-auto d-none d-lg-block"
          src="{{ latest_posts.0.thumbnail.url }}" alt="Card image cap">
      {% endif %}
    </div>
  </div>
</div>

<div class="row mb-2">
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-primary">Blog</strong>
        {% if latest_posts.1 %}
          <h3 class="mb-0">
            <a href="{% url 'blog:post_detail' pk=latest_posts.1.pk %}" class="text-dark">
              {{ latest_posts.1.title }}</a>
          </h3>
          <div class="mb-1 text-muted">{{ latest_posts.1.publish_date }}</div>
          <p class="card-text mb-auto">
            {{ latest_posts.1.text|render_markdown|safe|truncatewords:15 }}
          </p>
          <a href="{% url 'blog:post_detail' pk=latest_posts.1.pk %}">Continue reading</a>
        {% endif %}
      </div>
      {% if latest_posts.1.thumbnail %}
        <img class="card-img-right flex-auto d-none d-lg-block"
          src="{{ latest_posts.1.thumbnail.url }}" alt="Card image cap">
      {% endif %}
    </div>
  </div>
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-success">Projects</strong>
        {% if latest_posts.2 %}
          <h3 class="mb-0">
            <a href="{% url 'blog:post_detail' pk=latest_posts.2.pk %}" class="text-dark">
              {{ latest_posts.2.title }}</a>
          </h3>
          <div class="mb-1 text-muted">{{ latest_posts.2.publish_date }}</div>
          <p class="card-text mb-auto">
            {{ latest_posts.2.text|render_markdown|safe|truncatewords:15 }}
          </p>
          <a href="{% url 'blog:post_detail' pk=latest_posts.2.pk %}">Continue reading</a>
        {% endif %}
      </div>
      {%if latest_posts.2.thumbnail%}
        <img class="card-img-right flex-auto d-none d-lg-block"
          src="{{ latest_posts.2.thumbnail.url }}" alt="Card image cap">
      {% endif %}
    </div>
  </div>
</div>
</div>
{% endblock %}